# ===== 快捷栏标题控制器 =====

# --- 初始化 ---
## 获取怪物和玩家数目
function lib/get_monster_amount
function lib/get_player_amount

# --- 获取玩家当前位置和当前关卡进度 ---
execute @a ~~~ function lib/get_entity_location
execute @e[name=level] ~~~ scoreboard players operation @s temp = @s data
execute @e[name=level] ~~~ function lib/3_digit_seperator
execute @a ~~~ scoreboard players operation @s temp = @s inLevelArea
execute @a ~~~ function lib/3_digit_seperator



## --- 正在进行的关卡 ---
## temp3.level=0 | 每5tick显示一次


### 玩家数为1时，不显示玩家数量
execute @e[name=tick,scores={time=!0..4,time=!6..10,time=!11..15,time=!16..20}] ~~~ execute @e[name=allPlayersAmount,scores={data=1}] ~~~ function system/level_controllers/actionbar_singleplayer
### 玩家数大于1时，显示玩家数量
execute @e[name=tick,scores={time=!0..4,time=!6..10,time=!11..15,time=!16..20}] ~~~ execute @e[name=allPlayersAmount,scores={data=2..}] ~~~ function system/level_controllers/actionbar_multiplayer

## --- 已完成的关卡 ---
## temp3.level=1 | 每5tick显示一次

### 当玩家在正常关卡区域时，显示对应关卡编号 | 7-0时会有一段时间设定为701，此时不应该显示
execute @e[name=tick,scores={time=!0..4,time=!6..10,time=!11..15,time=!16..20}] ~~~ execute @e[name=level,scores={temp3=1,data=!701}] ~~~ execute @a[scores={temp2=1..,temp3=1..7}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| §a✔ 关卡已完成","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}},{"score":{"objective":"temp3","name":"@s"}}]}}]}

execute @e[name=tick,scores={time=!0..4,time=!6..10,time=!11..15,time=!16..20}] ~~~ execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=1,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s \n§e沙漠神殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=tick,scores={time=!0..4,time=!6..10,time=!11..15,time=!16..20}] ~~~ execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=2,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s \n§a丛林神殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=tick,scores={time=!0..4,time=!6..10,time=!11..15,time=!16..20}] ~~~ execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=3,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s \n§b湖泊神殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=tick,scores={time=!0..4,time=!6..10,time=!11..15,time=!16..20}] ~~~ execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=4,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s \n§3寒冰神殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=tick,scores={time=!0..4,time=!6..10,time=!11..15,time=!16..20}] ~~~ execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=5,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s \n§f红石神殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=tick,scores={time=!0..4,time=!6..10,time=!11..15,time=!16..20}] ~~~ execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=6,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s \n§7山峦神殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=tick,scores={time=!0..4,time=!6..10,time=!11..15,time=!16..20}] ~~~ execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=6,temp3=9}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§f§l剑之神殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=tick,scores={time=!0..4,time=!6..10,time=!11..15,time=!16..20}] ~~~ execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=7,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s \n§c封印神殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}


### 无效位置提示 | 仅开发版
execute @e[name=developerMode,scores={settings=1}] ~~~ execute @a[scores={inLevelArea=-1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§c错误：无法检测的位置"}]}

# --- 单人情况下的记分板 ---
execute @e[name=level,scores={temp3=0}] ~~~ execute @a[scores={temp2=1}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a1-%%s §f| §e沙漠神殿\n\n§r§f☠ 怪物数： §a%%s§7/%%s\n§r§f☺ 玩家数： §a%%s§7/%%s\n§r§f波数 §a█§e█§7█\n\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "data", "name": "@e[name=monsterAmount]" } }, { "score": { "objective": "data", "name": "maxMonsterAmount" } },{ "score": { "objective": "data", "name": "@e[name=alivePlayersAmount]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }
execute @e[name=level,scores={temp3=0}] ~~~ execute @a[scores={temp2=2}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a2-%%s §f| §a丛林神殿\n\n§r§f☠ 怪物数： §a%%s§7/%%s\n§r§f☺ 玩家数： §a%%s§7/%%s\n§r§f波数 §a█§e█§7█\n\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "data", "name": "@e[name=monsterAmount]" } }, { "score": { "objective": "data", "name": "maxMonsterAmount" } },{ "score": { "objective": "data", "name": "@e[name=alivePlayersAmount]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }
execute @e[name=level,scores={temp3=0}] ~~~ execute @a[scores={temp2=3}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a3-%%s §f| §b湖泊神殿\n\n§r§f☠ 怪物数： §a%%s§7/%%s\n§r§f☺ 玩家数： §a%%s§7/%%s\n§r§f波数 §a█§e█§7█\n\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "data", "name": "@e[name=monsterAmount]" } }, { "score": { "objective": "data", "name": "maxMonsterAmount" } },{ "score": { "objective": "data", "name": "@e[name=alivePlayersAmount]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }
execute @e[name=level,scores={temp3=0}] ~~~ execute @a[scores={temp2=4}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a4-%%s §f| §3寒冰神殿\n\n§r§f☠ 怪物数： §a%%s§7/%%s\n§r§f☺ 玩家数： §a%%s§7/%%s\n§r§f波数 §a█§e█§7█\n\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "data", "name": "@e[name=monsterAmount]" } }, { "score": { "objective": "data", "name": "maxMonsterAmount" } },{ "score": { "objective": "data", "name": "@e[name=alivePlayersAmount]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }
execute @e[name=level,scores={temp3=0}] ~~~ execute @a[scores={temp2=5}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a5-%%s §f| §f红石神殿\n\n§r§f☠ 怪物数： §a%%s§7/%%s\n§r§f☺ 玩家数： §a%%s§7/%%s\n§r§f波数 §a█§e█§7█\n\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "data", "name": "@e[name=monsterAmount]" } }, { "score": { "objective": "data", "name": "maxMonsterAmount" } },{ "score": { "objective": "data", "name": "@e[name=alivePlayersAmount]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }
execute @e[name=level,scores={temp3=0}] ~~~ execute @a[scores={temp2=6}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a6-%%s §f| §7山峦神殿\n\n§r§f☠ 怪物数： §a%%s§7/%%s\n§r§f☺ 玩家数： §a%%s§7/%%s\n§r§f波数 §a█§e█§7█\n\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "data", "name": "@e[name=monsterAmount]" } }, { "score": { "objective": "data", "name": "maxMonsterAmount" } },{ "score": { "objective": "data", "name": "@e[name=alivePlayersAmount]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }
execute @e[name=level,scores={temp3=0}] ~~~ execute @a[scores={temp2=7}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a7-%%s §f| §c封印神殿\n\n§r§f☠ 怪物数： §a%%s§7/%%s\n§r§f☺ 玩家数： §a%%s§7/%%s\n§r§f波数 §a█§e█§7█\n\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "data", "name": "@e[name=monsterAmount]" } }, { "score": { "objective": "data", "name": "maxMonsterAmount" } },{ "score": { "objective": "data", "name": "@e[name=alivePlayersAmount]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }

execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=1}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a1-%%s §f| §e沙漠神殿\n§r关卡进度 §a%%s-%%s\n\n§r§f☺ 玩家数： §a%%s\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "temp", "name": "@e[name=level]" } }, { "score": { "objective": "temp2", "name": "@e[name=level]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=2}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a2-%%s §f| §a丛林神殿\n§r关卡进度 §a%%s-%%s\n\n§r§f☺ 玩家数： §a%%s\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "temp", "name": "@e[name=level]" } }, { "score": { "objective": "temp2", "name": "@e[name=level]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=3}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a3-%%s §f| §b湖泊神殿\n§r关卡进度 §a%%s-%%s\n\n§r§f☺ 玩家数： §a%%s\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "temp", "name": "@e[name=level]" } }, { "score": { "objective": "temp2", "name": "@e[name=level]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=4}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a4-%%s §f| §3寒冰神殿\n§r关卡进度 §a%%s-%%s\n\n§r§f☺ 玩家数： §a%%s\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "temp", "name": "@e[name=level]" } }, { "score": { "objective": "temp2", "name": "@e[name=level]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=5}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a5-%%s §f| §f红石神殿\n§r关卡进度 §a%%s-%%s\n\n§r§f☺ 玩家数： §a%%s\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "temp", "name": "@e[name=level]" } }, { "score": { "objective": "temp2", "name": "@e[name=level]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=6}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a6-%%s §f| §7山峦神殿\n§r关卡进度 §a%%s-%%s\n\n§r§f☺ 玩家数： §a%%s\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "temp", "name": "@e[name=level]" } }, { "score": { "objective": "temp2", "name": "@e[name=level]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=7}] ~~~ titleraw @s actionbar { "rawtext": [ { "translate": "§l§e冒险小世界§b：剑之试炼\n\n§r关卡 §a7-%%s §f| §c封印神殿\n§r关卡进度 §a%%s-%%s\n\n§r§f☺ 玩家数： §a%%s\n§r§f击杀数： §a%%s\n§r§f死亡数： §a%%s\n\n§r§f游玩时长： §a%%s:%%s", "with": { "rawtext": [ { "score": { "objective": "temp3", "name": "@s" } }, { "score": { "objective": "temp", "name": "@e[name=level]" } }, { "score": { "objective": "temp2", "name": "@e[name=level]" } }, { "score": { "objective": "data", "name": "@e[name=allPlayersAmount]" } }, { "score": { "objective": "killAmount", "name": "@s" } }, { "score": { "objective": "deathTimes", "name": "@s" } }, { "score": { "objective": "time", "name": "@e[name=playedMinute]" } }, { "score": { "objective": "time", "name": "@e[name=playedSecond]" } } ] } } ] }

## --- 特殊快捷栏标题 ---

### 物品快捷栏标题
function system/level_controllers/actionbar_items
