# ===== 多人模式下的快捷栏标题显示 =====

## --- 最大1波的关卡 ---
## 需要额外除去4-4的显示
execute @e[name=level,scores={temp3=0,data=!440}] ~~~ execute @e[name=maxWave,scores={data=1}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0,data=!440}] ~~~ execute @e[name=maxWave,scores={data=1}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

## --- 最大2波的关卡 ---
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=2}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=2}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=2}] ~~~ execute @e[name=wave,scores={data=2}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a█§e█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=2}] ~~~ execute @e[name=wave,scores={data=2}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a█§e█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

## --- 最大3波的关卡 ---
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=3}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█§7██ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=3}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█§7██","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=3}] ~~~ execute @e[name=wave,scores={data=2}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a█§e█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=3}] ~~~ execute @e[name=wave,scores={data=2}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a█§e█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=3}] ~~~ execute @e[name=wave,scores={data=3}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a██§e█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=3}] ~~~ execute @e[name=wave,scores={data=3}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a██§e█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

## --- 最大4波的关卡 ---
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=4}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█§7███ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=4}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█§7███","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=4}] ~~~ execute @e[name=wave,scores={data=2}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a█§e█§7██ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=4}] ~~~ execute @e[name=wave,scores={data=2}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a█§e█§7██","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=4}] ~~~ execute @e[name=wave,scores={data=3}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a██§e█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=4}] ~~~ execute @e[name=wave,scores={data=3}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a██§e█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=4}] ~~~ execute @e[name=wave,scores={data=4}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a███§e█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=4}] ~~~ execute @e[name=wave,scores={data=4}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a███§e█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

## --- 最大5波的关卡 ---
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=5}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█§7████ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=5}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█§7████","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=5}] ~~~ execute @e[name=wave,scores={data=2}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a█§e█§7███ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=5}] ~~~ execute @e[name=wave,scores={data=2}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a█§e█§7███","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=5}] ~~~ execute @e[name=wave,scores={data=3}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a██§e█§7██ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=5}] ~~~ execute @e[name=wave,scores={data=3}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a██§e█§7██","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=5}] ~~~ execute @e[name=wave,scores={data=4}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a███§e█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=5}] ~~~ execute @e[name=wave,scores={data=4}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a███§e█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=5}] ~~~ execute @e[name=wave,scores={data=5}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a████§e█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={data=5}] ~~~ execute @e[name=wave,scores={data=5}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a████§e█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

## --- 特殊关卡 ---

### 2-3 - 有boss
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=230}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█§7██§c█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=230}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█§7██§c█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=230}] ~~~ execute @e[name=wave,scores={data=2}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a█§e█§7█§c█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=230}] ~~~ execute @e[name=wave,scores={data=2}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a█§e█§7█§c█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=230}] ~~~ execute @e[name=wave,scores={data=3}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a██§e█§c█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=230}] ~~~ execute @e[name=wave,scores={data=3}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a██§e█§c█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=230}] ~~~ execute @e[name=wave,scores={data=4}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a███§6█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=230}] ~~~ execute @e[name=wave,scores={data=4}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a███§6█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

### 3-4 - 有boss
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=340}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█§7█§c█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=340}] ~~~ execute @e[name=wave,scores={data=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█§7█§c█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=340}] ~~~ execute @e[name=wave,scores={data=2}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a█§e█§c█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=340}] ~~~ execute @e[name=wave,scores={data=2}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a█§e█§c█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=340}] ~~~ execute @e[name=wave,scores={data=3}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a██§6█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=340}] ~~~ execute @e[name=wave,scores={data=3}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a██§6█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=340}] ~~~ execute @e[name=wave,scores={data=4}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a██§b█§e█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=340}] ~~~ execute @e[name=wave,scores={data=4}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a██§b█§e█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"maxMonsterAmount"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}}]}}]}

### 4-4 - 特殊玩法
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=440}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s | ☺ §c%%s§7/%%s §f| ☹ %%ss/§7180s §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}},{"score":{"objective":"time","name":"@e[name=timeLeft]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={data=440}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s | ☺ §f%%s§7/%%s §f| ☹ %%ss/§7180s","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"data","name":"@e[name=monsterAmount]"}},{"score":{"objective":"data","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"data","name":"@e[name=allPlayersAmount]"}},{"score":{"objective":"time","name":"@e[name=timeLeft]"}}]}}]}

