# ===== 快捷栏标题控制器 =====

## --- 初始化 ---
### 获取怪物和玩家数目
function methods/get_monster_amount
function methods/get_player_amount

## --- 正在进行的关卡 ---
## temp3.level=0

### 最大1波的关卡
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=1}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=1}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

### 最大2波的关卡
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=2}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=2}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=2}] ~~~ execute @e[name=wave,scores={background=2}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a█§e█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=2}] ~~~ execute @e[name=wave,scores={background=2}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a█§e█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

### 最大3波的关卡
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=3}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█§7██ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=3}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█§7██","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=3}] ~~~ execute @e[name=wave,scores={background=2}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a█§e█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=3}] ~~~ execute @e[name=wave,scores={background=2}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a█§e█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=3}] ~~~ execute @e[name=wave,scores={background=3}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a██§e█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=3}] ~~~ execute @e[name=wave,scores={background=3}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a██§e█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

### 最大4波的关卡
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=4}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█§7███ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=4}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█§7███","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=4}] ~~~ execute @e[name=wave,scores={background=2}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a█§e█§7██ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=4}] ~~~ execute @e[name=wave,scores={background=2}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a█§e█§7██","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=4}] ~~~ execute @e[name=wave,scores={background=3}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a██§e█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=4}] ~~~ execute @e[name=wave,scores={background=3}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a██§e█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=4}] ~~~ execute @e[name=wave,scores={background=4}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a███§e█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=4}] ~~~ execute @e[name=wave,scores={background=4}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a███§e█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

### 最大5波的关卡
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=5}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█§7████ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=5}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█§7████","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=5}] ~~~ execute @e[name=wave,scores={background=2}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a█§e█§7███ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=5}] ~~~ execute @e[name=wave,scores={background=2}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a█§e█§7███","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=5}] ~~~ execute @e[name=wave,scores={background=3}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a██§e█§7██ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=5}] ~~~ execute @e[name=wave,scores={background=3}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a██§e█§7██","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=5}] ~~~ execute @e[name=wave,scores={background=4}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a███§e█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=5}] ~~~ execute @e[name=wave,scores={background=4}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a███§e█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=5}] ~~~ execute @e[name=wave,scores={background=5}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a████§e█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=maxWave,scores={background=5}] ~~~ execute @e[name=wave,scores={background=5}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a████§e█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

### 特殊关卡：带有BOSS的关卡

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=230}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█§7██§c█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=230}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█§7██§c█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=230}] ~~~ execute @e[name=wave,scores={background=2}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a█§e█§7█§c█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=230}] ~~~ execute @e[name=wave,scores={background=2}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a█§e█§7█§c█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=230}] ~~~ execute @e[name=wave,scores={background=3}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a██§e█§c█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=230}] ~~~ execute @e[name=wave,scores={background=3}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a██§e█§c█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=230}] ~~~ execute @e[name=wave,scores={background=4}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a███§6█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=230}] ~~~ execute @e[name=wave,scores={background=4}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a███§6█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=340}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §e█§7█§c█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=340}] ~~~ execute @e[name=wave,scores={background=1}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §e█§7█§c█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=340}] ~~~ execute @e[name=wave,scores={background=2}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a█§e█§c█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=340}] ~~~ execute @e[name=wave,scores={background=2}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a█§e█§c█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=340}] ~~~ execute @e[name=wave,scores={background=3}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a██§6█§7█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=340}] ~~~ execute @e[name=wave,scores={background=3}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a██§6█§7█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=340}] ~~~ execute @e[name=wave,scores={background=4}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §c%%s§7/%%s §f| §a██§b█§e█ §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=340}] ~~~ execute @e[name=wave,scores={background=4}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s§7/%%s | ☺ §f%%s§7/%%s §f| §a██§b█§e█","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"maxMonsterAmount"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}}]}}]}

execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=440}] ~~~ execute @a[scores={isAlive=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s | ☺ §c%%s§7/%%s §f| ☹ %%ss/§7180s §r| §c观战中...","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}},{"score":{"objective":"time","name":"@e[name=timeLeft]"}}]}}]}
execute @e[name=level,scores={temp3=0}] ~~~ execute @e[name=level,scores={background=440}] ~~~ execute @a[scores={isAlive=1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| ☠ §f%%s | ☺ §f%%s§7/%%s §f| ☹ %%ss/§7180s","with":{"rawtext":[{"score":{"objective":"temp","name":"@e[name=level]"}},{"score":{"objective":"temp2","name":"@e[name=level]"}},{"score":{"objective":"background","name":"@e[name=monsterAmount]"}},{"score":{"objective":"background","name":"@e[name=alivePlayersAmount]"}},{"score":{"objective":"background","name":"@e[name=allPlayersAmount]"}},{"score":{"objective":"time","name":"@e[name=timeLeft]"}}]}}]}


## --- 已完成的关卡 ---
## temp3.level=1

### 当玩家在正常关卡区域时，显示对应关卡编号
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp3=1..8}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s-%%s §r§f| §a✔ 关卡已完成","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}},{"score":{"objective":"temp3","name":"@s"}}]}}]}

execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=1,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s §r§f| §e§l沙 漠 神 殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=2,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s §r§f| §a§l丛 林 神 殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=3,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s §r§f| §b§l湖 泊 神 殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=4,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s §r§f| §3§l寒 冰 神 殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=5,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s §r§f| §f§l红 石 神 殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=6,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s §r§f| §7§l山 峦 神 殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=6,temp3=9}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§f§l剑 之 神 殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}
execute @e[name=level,scores={temp3=1}] ~~~ execute @a[scores={temp2=7,temp3=0}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§l%%s §r§f| §c§l封 印 神 殿","with":{"rawtext":[{"score":{"objective":"temp2","name":"@s"}}]}}]}

## --- 特殊快捷栏标题 ---

### 物品快捷栏标题
function items/actionbar_title

### 玩家手持物品提示
execute @e[name=level,scores={background=311..}] ~~~ titleraw @a[scores={isHoldingHelmet=0}] actionbar {"rawtext":[{"text":"§c您刚刚获得了一个钻石头盔，请手持钻石头盔以获取附魔！"}]}
execute @e[name=level,scores={background=321..}] ~~~ titleraw @a[scores={isHoldingBoots=0}] actionbar {"rawtext":[{"text":"§c您刚刚获得了一个钻石靴子，请手持钻石靴子以获取附魔！"}]}

### 无效位置提示 | 仅开发版
execute @e[name=developerMode,scores={settings=1}] ~~~ execute @a[scores={inLevelArea=-1}] ~~~ titleraw @s actionbar {"rawtext":[{"translate":"§c错误：无法检测的位置"}]}



### 调试性内容
# titleraw @a actionbar {"rawtext":[{"translate":"wave=%%s | lastWaveCompleted=%%s | monsterSummonDelay=%%s","with":{"rawtext":[{"score":{"objective":"background","name":"@e[name=wave]"}},{"score":{"objective":"background","name":"@e[name=lastWaveCompleted]"}},{"score":{"objective":"time","name":"@e[name=monsterSummonDelay]"}}]}}]}