# 快捷栏标题控制器

execute @e[name=level,scores={stats=100..109}] ~~~ function levels/1_0/actionbar_title
execute @e[name=level,scores={stats=110..119}] ~~~ function levels/1_1/actionbar_title
execute @e[name=level,scores={stats=120..129}] ~~~ function levels/1_2/actionbar_title
execute @e[name=level,scores={stats=130..139}] ~~~ function levels/1_3/actionbar_title
execute @e[name=level,scores={stats=200..209}] ~~~ function levels/2_0/actionbar_title
execute @e[name=level,scores={stats=210..219}] ~~~ function levels/2_1/actionbar_title
execute @e[name=level,scores={stats=220..229}] ~~~ function levels/2_2/actionbar_title
execute @e[name=level,scores={stats=230..239}] ~~~ function levels/2_3/actionbar_title
execute @e[name=level,scores={stats=300..309}] ~~~ function levels/3_0/actionbar_title
execute @e[name=level,scores={stats=310..319}] ~~~ function levels/3_1/actionbar_title
execute @e[name=level,scores={stats=320..329}] ~~~ function levels/3_2/actionbar_title
execute @e[name=level,scores={stats=330..339}] ~~~ function levels/3_3/actionbar_title
execute @e[name=level,scores={stats=340..349}] ~~~ function levels/3_4/actionbar_title
execute @e[name=level,scores={stats=400..409}] ~~~ function levels/4_0/actionbar_title
execute @e[name=level,scores={stats=410..419}] ~~~ function levels/4_1/actionbar_title
execute @e[name=level,scores={stats=420..429}] ~~~ function levels/4_2/actionbar_title
execute @e[name=level,scores={stats=430..439}] ~~~ function levels/4_3/actionbar_title
execute @e[name=level,scores={stats=440..449}] ~~~ function levels/4_4/actionbar_title
execute @e[name=level,scores={stats=500..509}] ~~~ function levels/5_0/actionbar_title
execute @e[name=level,scores={stats=600..609}] ~~~ function levels/6_0/actionbar_title
execute @e[name=level,scores={stats=610..619}] ~~~ function levels/6_1/actionbar_title
execute @e[name=level,scores={stats=620..629}] ~~~ function levels/6_2/actionbar_title
execute @e[name=level,scores={stats=630..639}] ~~~ function levels/6_3/actionbar_title
execute @e[name=level,scores={stats=640..649}] ~~~ function levels/6_4/actionbar_title
execute @e[name=level,scores={stats=700..709}] ~~~ function levels/7_0/actionbar_title
execute @e[name=level,scores={stats=710..719}] ~~~ function levels/7_1/actionbar_title
execute @e[name=level,scores={stats=720..729}] ~~~ function levels/7_2/actionbar_title
execute @e[name=level,scores={stats=730..739}] ~~~ function levels/7_3/actionbar_title
execute @e[name=level,scores={stats=740..749}] ~~~ function levels/7_4/actionbar_title
execute @e[name=level,scores={stats=750..759}] ~~~ function levels/7_5/actionbar_title